// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net_Elsayed_Mohammed_Elsayed_Ali_Leilla.Data;

namespace Net_Elsayed_Mohammed_Elsayed_Ali_Leilla.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Net_Elsayed_Mohammed_Elsayed_Ali_Leilla.Models.Table_Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailConfirmationToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Table_Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AddedDate = new DateTime(2020, 4, 22, 21, 28, 0, 351, DateTimeKind.Local).AddTicks(8319),
                            Email = "elsayed.mohammed70@gmail.com",
                            EmailConfirmationToken = "74888817",
                            IsEmailConfirmed = false,
                            LastName = "TestLeilla",
                            Name = "Test Elsayed Mohammed",
                            Password = "123",
                            PhoneNumber = "01069879123",
                            Username = "TestElsyed_Leilla"
                        },
                        new
                        {
                            UserId = 2,
                            AddedDate = new DateTime(2020, 4, 22, 21, 28, 0, 351, DateTimeKind.Local).AddTicks(9631),
                            Email = "elsayed.mohammed70@gmail.com",
                            EmailConfirmationToken = "708fa6f",
                            IsEmailConfirmed = false,
                            LastName = "TestLeilla",
                            Name = "Test Elsayed Ali",
                            Password = "1321",
                            PhoneNumber = "01076566765",
                            Username = "TestElsyed_Ali"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
